---
- name: Podwatch
  connection: local
  hosts: localhost
  gather_facts: false
  # Switch to false if podman containers are running as a regular user
  become: true
  tasks:
  - name: Get all container images
    containers.podman.podman_image_info:
    register: r_images

  - name: Update Container Images and restart containers
    when: r_images.images | length > 0
    vars:
      _image_name: "{{ item.RepoTags[0] }}"
      _image_sha: "{{ item.Id }}"
    include_tasks: update_image_restart_container.yml
    loop: "{{ r_images.images }}"
    loop_control:
      label: "{{ item.RepoTags[0] }}"

  - name: Podman cleanup
    command: podman system prune --force
